### ISSUE TITLE
Datetime is not supported in associations method

### ISSUE THREAD

**Issue by shakedzy** [shakedzy/dython#76]
When using `nominal.associations` over data that contains `datetime` data, an error occurs:
```python
import pandas as pd
from datetime import datetime, timedelta
from dython.nominal import associations

dt = datetime(2020, 12, 1)
end = datetime(2020, 12, 2)
step = timedelta(seconds=5)
result = []
while dt < end:
    result.append(dt.strftime('%Y-%m-%d %H:%M:%S'))
    dt += step

nums = list(range(len(result)))
df = pd.DataFrame({'dates':result, 'up': nums, 'down': sorted(nums, reverse=True)})
df['dates'] = pd.to_datetime(df['dates'], format="%Y-%m-%d %H:%M:%S")  # without this, this column is considered as object rather than dates

associations(df)
```

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shaked.z/self/dython/dython/nominal.py", line 559, in associations
    nan_strategy, nan_replace_value)
  File "/Users/shaked.z/self/dython/dython/nominal.py", line 373, in _comp_assoc
    dataset[columns[j]])
  File "/Users/shaked.z/myenv/lib/python3.6/site-packages/scipy/stats/stats.py", line 3851, in pearsonr
    dtype = type(1.0 + x[0] + y[0])
numpy.core._exceptions.UFuncTypeError: ufunc 'add' cannot use operands with types dtype('float64') and dtype('<M8[ns]')
```

Dates and times should be considered as continuous numerical values.

**Comment by shakedzy** [comment]
Fixed in version 0.6.6
